/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'board-history': BoardHistory;
    committees: Committee;
    documents: Document;
    'election-cycles': ElectionCycle;
    events: Event;
    faqs: Faq;
    'gallery-images': GalleryImage;
    media: Media;
    pages: Page;
    people: Person;
    'student-groups': StudentGroup;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'board-history': BoardHistorySelect<false> | BoardHistorySelect<true>;
    committees: CommitteesSelect<false> | CommitteesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'election-cycles': ElectionCyclesSelect<false> | ElectionCyclesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'student-groups': StudentGroupsSelect<false> | StudentGroupsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-history".
 */
export interface BoardHistory {
  id: number;
  /**
   * e.g., "2023-2024"
   */
  academicYear: string;
  /**
   * Board groups for this year (Executives, Directors, etc.)
   */
  groups: {
    /**
     * e.g., "Executives", "Program Directors", "First Year Directors"
     */
    groupName: string;
    /**
     * Members of this board group
     */
    members: (number | Person)[];
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  email?: string | null;
  /**
   * e.g., "VP Academics", "Biology Director", etc.
   */
  position: string;
  /**
   * Biography or candidate statement (supports HTML formatting)
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Profile photo
   */
  photo?: (number | null) | Media;
  /**
   * Academic year, e.g., "2023-2024"
   */
  year?: string | null;
  /**
   * Role classification
   */
  type: 'executive' | 'director' | 'committee-member' | 'candidate' | 'past-board';
  /**
   * Current status of the person
   */
  status: 'active' | 'past' | 'candidate';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees".
 */
export interface Committee {
  id: number;
  /**
   * e.g., "Academics", "Board of Directors", "Communications"
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Committee description and responsibilities
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Current committee members
   */
  members?: (number | Person)[] | null;
  /**
   * Committee images for carousel display
   */
  images?: (number | Media)[] | null;
  /**
   * Academic year, e.g., "2023-2024"
   */
  year?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Document title
   */
  title: string;
  /**
   * Document category
   */
  category: 'governance' | 'budget' | 'elections' | 'policies' | 'other';
  /**
   * PDF or document file
   */
  file: number | Media;
  /**
   * Brief description of the document
   */
  description?: string | null;
  /**
   * Date the document was last updated
   */
  lastUpdated?: string | null;
  /**
   * Relevant academic year (e.g., "2023-2024")
   */
  academicYear?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "election-cycles".
 */
export interface ElectionCycle {
  id: number;
  /**
   * e.g., "2025-2026"
   */
  academicYear: string;
  /**
   * URL-friendly identifier, e.g., "elections2025"
   */
  slug: string;
  /**
   * Is this the current/active election cycle?
   */
  isActive?: boolean | null;
  /**
   * Election schedule image or document
   */
  schedule?: (number | null) | Media;
  /**
   * Chief Returning Officer (CRO) information image
   */
  croInfo?: (number | null) | Media;
  /**
   * Candidates running in this election
   */
  candidates?: (number | Person)[] | null;
  /**
   * Link to election results document
   */
  resultsDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Event description (supports HTML)
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Type of event
   */
  eventType: 'annual' | 'formal' | 'orientation' | 'gallery' | 'other';
  /**
   * Event date
   */
  date?: string | null;
  /**
   * Academic year or calendar year, e.g., "2023"
   */
  year?: string | null;
  /**
   * Event images
   */
  images?: (number | Media)[] | null;
  /**
   * Display on homepage or featured areas
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * The FAQ question
   */
  question: string;
  /**
   * The answer (supports HTML links and formatting)
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional category for grouping FAQs
   */
  category?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  /**
   * Display this FAQ on the homepage (limit to first 8)
   */
  showOnHomepage?: boolean | null;
  /**
   * Publish this FAQ
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  /**
   * Image caption or title
   */
  title: string;
  /**
   * Gallery image
   */
  image: number | Media;
  /**
   * Year the photo was taken, e.g., "2023"
   */
  year: string;
  /**
   * Associated event (optional)
   */
  event?: (number | null) | Event;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  /**
   * Feature this image in galleries
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Page title
   */
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Mark this page as the homepage
   */
  isHomepage?: boolean | null;
  /**
   * Page status
   */
  status: 'draft' | 'published';
  /**
   * Publication date
   */
  publishedAt?: string | null;
  blocks: (
    | {
        /**
         * Main hero title (e.g., "USSTM")
         */
        title: string;
        /**
         * Hero subtitle text
         */
        subtitle?: string | null;
        /**
         * Organization motto
         */
        motto?: string | null;
        /**
         * Parallax background image (optional)
         */
        backgroundImage?: (number | null) | Media;
        /**
         * Background overlay opacity (0-1)
         */
        overlayOpacity?: number | null;
        textAlignment?: ('left' | 'center' | 'right') | null;
        stats?:
          | {
              label: string;
              /**
               * Stat value (e.g., "4000")
               */
              value: string;
              /**
               * Optional suffix (e.g., "+")
               */
              suffix?: string | null;
              /**
               * Icon image for this stat
               */
              icon?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Full-featured rich text content
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        /**
         * About Us heading
         */
        heading?: string | null;
        /**
         * About Us content
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutUs';
      }
    | {
        /**
         * Section heading
         */
        heading?: string | null;
        /**
         * Section subheading
         */
        subheading?: string | null;
        /**
         * Section content
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        backgroundColor?: ('none' | 'background' | 'highlight' | 'highlight-blue' | 'highlight-dark') | null;
        alignment?: ('left' | 'center' | 'right' | 'justify') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textSection';
      }
    | {
        image: number | Media;
        /**
         * Alternative text for accessibility
         */
        alt: string;
        /**
         * Optional image caption
         */
        caption?: string | null;
        size?: ('small' | 'medium' | 'large' | 'full') | null;
        alignment?: ('left' | 'center' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        /**
         * FAQ section heading
         */
        heading?: string | null;
        /**
         * FAQ section subheading
         */
        subheading?: string | null;
        /**
         * Select FAQs to display
         */
        faqs?: (number | Faq)[] | null;
        /**
         * Maximum number of FAQs to display (leave empty for all)
         */
        displayLimit?: number | null;
        /**
         * URL for "View More" link (e.g., "/faq")
         */
        viewMoreLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        /**
         * Team section heading
         */
        heading?: string | null;
        /**
         * Select people to display
         */
        people?: (number | Person)[] | null;
        columns?: ('2' | '3' | '4') | null;
        /**
         * Show contact information for team members
         */
        showContactInfo?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamGrid';
      }
    | {
        /**
         * Committee section heading
         */
        heading?: string | null;
        /**
         * Select committees to display
         */
        committees?: (number | Committee)[] | null;
        displayStyle?: ('grid' | 'carousel') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'committeeShowcase';
      }
    | {
        /**
         * Events section heading
         */
        heading?: string | null;
        /**
         * Select events to display
         */
        events?: (number | Event)[] | null;
        displayStyle?: ('grid' | 'list') | null;
        /**
         * Show event dates
         */
        showDate?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'eventsGrid';
      }
    | {
        /**
         * Gallery section heading
         */
        heading?: string | null;
        /**
         * Select images for the gallery
         */
        images: (number | Media)[];
        layout?: ('grid' | 'masonry' | 'carousel') | null;
        columns?: ('2' | '3' | '4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        /**
         * Section heading
         */
        heading?: string | null;
        pillars: {
          /**
           * Pillar title (e.g., "CONSISTENCY")
           */
          title: string;
          /**
           * Pillar description
           */
          description: string;
          /**
           * Text color for back of card
           */
          textColor?: ('white' | 'dark') | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'fourPillars';
      }
    | {
        /**
         * Section heading
         */
        heading?: string | null;
        /**
         * Land acknowledgement content
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        backgroundColor?: ('none' | 'background' | 'highlight' | 'highlight-blue' | 'highlight-dark') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'landAcknowledgement';
      }
    | {
        stats: {
          label: string;
          value: string;
          /**
           * Optional suffix (e.g., "+")
           */
          suffix?: string | null;
          icon?: (number | null) | Media;
          id?: string | null;
        }[];
        layout?: ('horizontal' | 'vertical' | 'grid') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        /**
         * Section heading
         */
        heading?: string | null;
        cards: {
          title: string;
          description?: string | null;
          image?: (number | null) | Media;
          /**
           * Optional link URL
           */
          link?: string | null;
          id?: string | null;
        }[];
        columns?: ('2' | '3' | '4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        /**
         * Call-to-action heading
         */
        heading: string;
        /**
         * CTA description text
         */
        description?: string | null;
        buttons: {
          label: string;
          href: string;
          style?: ('default' | 'primary' | 'secondary' | 'outline') | null;
          id?: string | null;
        }[];
        alignment?: ('left' | 'center' | 'right') | null;
        backgroundColor?: ('none' | 'background' | 'highlight' | 'highlight-blue' | 'highlight-dark') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        /**
         * HTML or iframe embed code
         */
        embedCode: string;
        aspectRatio?: ('16/9' | '4/3' | '1/1' | 'auto') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'embed';
      }
  )[];
  /**
   * SEO title (leave empty to use page title)
   */
  metaTitle?: string | null;
  /**
   * SEO description
   */
  metaDescription?: string | null;
  /**
   * SEO image (Open Graph, Twitter Card)
   */
  metaImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-groups".
 */
export interface StudentGroup {
  id: number;
  /**
   * Full name of the student group
   */
  name: string;
  /**
   * Acronym or abbreviation (e.g., "PACS", "WiCS")
   */
  shortName?: string | null;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Group logo
   */
  logo?: (number | null) | Media;
  /**
   * Type of organization
   */
  type: 'sg' | 'cu';
  /**
   * Contact email address
   */
  contactEmail?: string | null;
  /**
   * Instagram handle (without @)
   */
  instagram?: string | null;
  /**
   * Website URL
   */
  website?: string | null;
  /**
   * Is this group currently active?
   */
  isActive?: boolean | null;
  /**
   * Group description and mission
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'board-history';
        value: number | BoardHistory;
      } | null)
    | ({
        relationTo: 'committees';
        value: number | Committee;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'election-cycles';
        value: number | ElectionCycle;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'student-groups';
        value: number | StudentGroup;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-history_select".
 */
export interface BoardHistorySelect<T extends boolean = true> {
  academicYear?: T;
  groups?:
    | T
    | {
        groupName?: T;
        members?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees_select".
 */
export interface CommitteesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  members?: T;
  images?: T;
  year?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  file?: T;
  description?: T;
  lastUpdated?: T;
  academicYear?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "election-cycles_select".
 */
export interface ElectionCyclesSelect<T extends boolean = true> {
  academicYear?: T;
  slug?: T;
  isActive?: T;
  schedule?: T;
  croInfo?: T;
  candidates?: T;
  resultsDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  eventType?: T;
  date?: T;
  year?: T;
  images?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  showOnHomepage?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  year?: T;
  event?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isHomepage?: T;
  status?: T;
  publishedAt?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              motto?: T;
              backgroundImage?: T;
              overlayOpacity?: T;
              textAlignment?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    suffix?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        aboutUs?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              heading?: T;
              subheading?: T;
              content?: T;
              backgroundColor?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              size?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              subheading?: T;
              faqs?: T;
              displayLimit?: T;
              viewMoreLink?: T;
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              heading?: T;
              people?: T;
              columns?: T;
              showContactInfo?: T;
              id?: T;
              blockName?: T;
            };
        committeeShowcase?:
          | T
          | {
              heading?: T;
              committees?: T;
              displayStyle?: T;
              id?: T;
              blockName?: T;
            };
        eventsGrid?:
          | T
          | {
              heading?: T;
              events?: T;
              displayStyle?: T;
              showDate?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              layout?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        fourPillars?:
          | T
          | {
              heading?: T;
              pillars?:
                | T
                | {
                    title?: T;
                    description?: T;
                    textColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        landAcknowledgement?:
          | T
          | {
              heading?: T;
              content?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    suffix?: T;
                    icon?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              alignment?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              embedCode?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  position?: T;
  bio?: T;
  photo?: T;
  year?: T;
  type?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-groups_select".
 */
export interface StudentGroupsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  logo?: T;
  type?: T;
  contactEmail?: T;
  instagram?: T;
  website?: T;
  isActive?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Site name displayed across the website
   */
  siteName: string;
  /**
   * Site logo for navbar
   */
  logo: number | Media;
  /**
   * Main navigation menu items
   */
  navigation: {
    /**
     * Menu item label
     */
    label: string;
    /**
     * Link URL (e.g., /about, /events)
     */
    href?: string | null;
    /**
     * Description shown in dropdown (optional)
     */
    description?: string | null;
    /**
     * Submenu items (optional)
     */
    submenu?:
      | {
          label: string;
          href: string;
          /**
           * Description for submenu item
           */
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Footer copyright text
   */
  footerText: string;
  /**
   * Brief description of the site
   */
  siteDescription?: string | null;
  /**
   * Vision statement for USSTM
   */
  vision?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Mission statement for USSTM
   */
  mission?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Primary contact email
   */
  contactEmail?: string | null;
  /**
   * Social media links
   */
  socialMedia?: {
    /**
     * Instagram handle or URL
     */
    instagram?: string | null;
    /**
     * TikTok handle or URL
     */
    tiktok?: string | null;
    /**
     * LinkedIn profile or URL
     */
    linkedin?: string | null;
  };
  /**
   * List of science programs
   */
  programs: {
    /**
     * Program name, e.g., "Biology", "Computer Science"
     */
    program: string;
    id?: string | null;
  }[];
  /**
   * Contact form request types
   */
  requestTypes: {
    /**
     * Display label for the request type
     */
    label: string;
    /**
     * Value to submit with the form
     */
    value: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        submenu?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  footerText?: T;
  siteDescription?: T;
  vision?: T;
  mission?: T;
  contactEmail?: T;
  socialMedia?:
    | T
    | {
        instagram?: T;
        tiktok?: T;
        linkedin?: T;
      };
  programs?:
    | T
    | {
        program?: T;
        id?: T;
      };
  requestTypes?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}